name: Chromatic publish

on:
  push:
    branches:
      - main
    paths:
      - src/components/**
      - src/stories/**
      - .storybook/**

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '17.4.0'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish on Chromatic
        run:
          npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
          --exit-once-uploaded --exit-zero-on-changes
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
